# version: '3'
# services:
postgres:
  image: "postgres:9.6-alpine"
  environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  # expose:
    # - "5432"
  ports:
    - "5432:5432"
  volumes:
    - ./volumes/postgres:/var/lib/postgresql/data

redis:
  image: "redis"
  expose:
    - "6379"

rabbitmq:
  image: "rabbitmq:3"
  environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
  expose:
    - "5672"

  # web:
  #   restart: always
  #   build: .
  #   image: bloogrox/kpi-notificator
  #   command: bash -c "python manage.py runserver 0.0.0.0:8000"
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - PYTHONUNBUFFERED=0
  #   depends_on:
  #     - postgres
  #     - redis
  #     - rabbitmq


#   celery-worker:
#     image: bloogrox/kpi-notificator
# #    restart: always
# #    build: .
#     command: celery -A kpi_notificator.celery_app:app worker -c 1 -l info
# #    command: bin/modd -f modd-celery.conf
# #    volumes:
# #      - .:/code
#     environment:
#       - C_FORCE_ROOT="true"
# #      - PYTHONUNBUFFERED=0
#     depends_on:
# #      - web
#       - postgres
#       - rabbitmq

#   celery-beat:
#     image: bloogrox/kpi-notificator
# #    restart: always
# #    build: .
#     command: celery -A kpi_notificator.celery_app:app beat -l info
# #    volumes:
# #      - .:/code
# #    environment:
# #      - PYTHONUNBUFFERED=0
#     depends_on:
# #      - web
#       - postgres
#       - rabbitmq

#  rqworker:
#    restart: always
#    build: .
#    command: python manage.py rqworker
#    volumes:
#      - .:/code
#    environment:
#      - PYTHONUNBUFFERED=0
#    depends_on:
#      - postgres
#      - redis
#      - rabbitmq

#  rqscheduler:
#    restart: always
#    build: .
#    command: python manage.py rqscheduler -i 1
#    volumes:
#      - .:/code
#    environment:
#      - PYTHONUNBUFFERED=0
#    depends_on:
#      - postgres
#      - redis
#      - rabbitmq
