# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0029_auto_20170812_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('operator', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('PR', 'PROBLEM')], max_length=2)),
                ('offer_id', models.PositiveIntegerField()),
                ('affiliate_id', models.PositiveIntegerField()),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trigger.Trigger')),
            ],
        ),
    ]
