# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggercheck',
            name='affiliate_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='triggercheck',
            name='offer_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
