# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0002_auto_20170912_1501'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='triggercheck',
            index_together=set([('trigger', 'offer_id', 'affiliate_id')]),
        ),
    ]
