# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0003_auto_20170912_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggercheck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
