# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20170328_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer_id', models.IntegerField()),
                ('affiliate_id', models.IntegerField()),
                ('value', models.FloatField()),
                ('status', models.CharField(choices=[('OK', 'OK'), ('PR', 'PROBLEM')], max_length=2)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Metric')),
            ],
        ),
    ]
