# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='key',
            field=models.CharField(choices=[('MIN_CR', 'MIN_CR'), ('MAX_CR', 'MAX_CR'), ('PACC', 'PACC'), ('CLICKS_ZERO_CONV', 'CLICKS_ZERO_CONV'), ('CAP_FILL', 'CAP_FILL')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
