# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_trigger_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='metric',
        ),
    ]
