# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_offer_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='gr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
