# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_offer_gr'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='one_goal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_offer', to='stats.Goal'),
        ),
    ]
