# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateuser',
            name='account_manager_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
