# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_offer_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='secondary_email',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='use_secondary',
            field=models.BooleanField(default=False),
        ),
    ]
