# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_auto_20170418_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='lookback',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_conversions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
