# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_auto_20170422_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='action',
            field=models.CharField(choices=[('off', 'Off'), ('only_email', 'Only Email'), ('pause_immediately', 'Pause Immediately'), ('pause_in_24h', 'Pause in 24h')], default='off', max_length=30),
        ),
    ]
