# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_auto_20170423_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='gr',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='key',
            field=models.CharField(choices=[('MIN_CR', 'MIN_CR'), ('MAX_CR', 'MAX_CR'), ('PACC', 'PACC'), ('CLICKS_ZERO_CONV', 'CLICKS_ZERO_CONV'), ('CAP_FILL', 'CAP_FILL'), ('MIN_GR', 'MIN_GR')], max_length=20),
        ),
    ]
