# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 23:44
from __future__ import unicode_literals

from django.db import migrations


def set_offer_gr_default_values(apps, schema_editor):
    Offer = apps.get_model("stats", "Offer")
    for offer in Offer.objects.all():
        offer.gr = 0.0
        offer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_auto_20170424_0244'),
    ]

    operations = [
        migrations.RunPython(set_offer_gr_default_values)
    ]
