# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_auto_20170424_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='notify_affiliate',
            field=models.BooleanField(default=False, verbose_name='Notify Affiliate?'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='gr',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Minimal Goal Conversion Threshold'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='lookback',
            field=models.PositiveIntegerField(default=1, verbose_name='Lookback Period (days)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_conversions',
            field=models.PositiveIntegerField(default=0, verbose_name='Min Conversions'),
        ),
    ]
