# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_auto_20170424_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='cap_fill',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='offer',
            name='clicks_if_zero_conv',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_cr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_cr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='offer',
            name='pacc',
            field=models.FloatField(default=0.0, verbose_name='Clicks Cost Loss'),
        ),
    ]
