# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0021_auto_20170426_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerKey',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
