# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0022_triggerkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
