# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0023_actiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.ActionType')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.TriggerKey')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set([('key', 'action_type')]),
        ),
    ]
