# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0024_auto_20170501_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.ActionType', verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='action',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.TriggerKey', verbose_name='Event'),
        ),
    ]
