# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0025_auto_20170523_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnapproveLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('offer_id', models.PositiveIntegerField()),
                ('affiliate_id', models.PositiveIntegerField()),
            ],
        ),
    ]
