# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0028_triggerchecklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggerchecklog',
            name='trigger_condition',
        ),
        migrations.DeleteModel(
            name='TriggerCheckLog',
        ),
    ]
