# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0030_auto_20170812_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='categories_str',
            field=models.TextField(default=''),
        ),
    ]
