# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0032_auto_20170814_0027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionType',
        ),
    ]
