# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0033_delete_actiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='incent',
        ),
    ]
