# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0036_delete_triggerkey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnapproveLog',
        ),
    ]
