# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0037_delete_unapprovelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='cap_fill',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='clicks_if_zero_conv',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='max_cr',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_cr',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='pacc',
        ),
    ]
