# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0038_auto_20170814_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metriclog',
            name='affiliate_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='metriclog',
            name='offer_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
