# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-17 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0039_auto_20170831_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='notify_affiliate',
        ),
    ]
