# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-17 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0042_remove_offer_lookback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='min_clicks',
        ),
    ]
