# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-17 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0043_remove_offer_min_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deleted', 'deleted')], default='active', max_length=7),
        ),
    ]
