# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-18 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0046_offer_last_active_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('paused', 'paused'), ('expired', 'expired'), ('deleted', 'deleted')], db_index=True, default='active', max_length=7),
        ),
    ]
