# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-08 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0047_auto_20171018_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='last_active_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
