# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trigger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_status', models.CharField(choices=[('OK', 'OK'), ('PR', 'PROBLEM')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='operations',
            field=models.ManyToManyField(related_name='actions', to='actions.Operation'),
        ),
        migrations.AddField(
            model_name='action',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trigger.Trigger'),
        ),
    ]
