# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-24 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='actions.Action'),
            preserve_default=False,
        ),
    ]
