# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-24 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_notificationreceivertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='receivers',
            field=models.ManyToManyField(to='actions.NotificationReceiverType'),
        ),
    ]
