# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_notification_receivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='actions.Action'),
        ),
    ]
