# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.PositiveIntegerField()),
                ('value', models.CharField(choices=[('', '')], max_length=32)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.Criteria')),
            ],
        ),
    ]
