# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0028_triggerchecklog'),
        ('action', '0002_actioncondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_status', models.CharField(choices=[('OK', 'OK'), ('PR', 'PROBLEM')], max_length=32)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.TriggerCondition')),
            ],
        ),
        migrations.RemoveField(
            model_name='actioncondition',
            name='criteria',
        ),
        migrations.DeleteModel(
            name='ActionCondition',
        ),
        migrations.DeleteModel(
            name='Criteria',
        ),
    ]
