# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_auto_20170810_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='operations',
            field=models.ManyToManyField(related_name='actions', to='action.Operation'),
        ),
    ]
