# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MinClicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('value', models.FloatField()),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metric.EntityType')),
            ],
        ),
    ]
