# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0027_triggercondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('value', models.FloatField()),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threshold.EntityType')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.TriggerCondition', verbose_name='Trigger')),
            ],
        ),
    ]
