# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitytype',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
