# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0002_entitytype_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.TriggerCondition'),
        ),
    ]
